from project1.help_function2 import  *
str=input("enter string")
print(return_str_whithout_a_or_A(str))
# for i in range (3):
#     print(return_reverse(str),end=' ')
# return_first_and_last_char (str)
# num=int(input("enter num you want to check if is prime"))
# print(return_if_num_is_prime(num))
# num1=float(input("enter num you want to round"))
# print(return_rounded_num(num1))
# age=int(input("enter age"))
# city=input("enter city")
# price=int (input("enter full price"))
# print(price-return_discount(city,age)*price)
# upper=int(input("enter upper border"))
# lower=int(input("enter lower border"))
# num=int(input("enter number of random num you want"))
# print(fill_random_between_a_and_b(upper,lower,num))
# num=int(input("enter positive num you want reverse"))
# print(num+return_reverse_num (num))
num=int(input("enter num you want reverse"))
print(return_length_of_num (num))