from objects.cours.object_2 import *
# Roy= Student(318860848,"roy vaygue",{'math':90,'history':80,'english':90,'bible':70})
# Ori= Student(206573057,"ori hasin",{'math':92,'history':70,'english':90,'bible':92})
# ami= Student(206573056,"ami hasin",{'math':92,'history':70,'english':90,'bible':92})
# Roy.add_grade("italian",98)
# print(Roy)
# print(Roy.list_of_grades.values())
# print(Roy.average())
# Roy.calc_factor('history',11)
# print(Roy.list_of_grades.values())
# C1=Course(1,"math",{'mor':'statistics'},[Roy,Ori],3)
# print(C1)
# print(C1.add_student(ami))
# print(C1)
# C1.del_student(206573056)
# print(C1)
# C1.add_factor('english',3)
C1=Course(1,"math",{"statistics":"michal"})
student=input("input id, name ")
while(student!='0'):
    C1.add_student(student)
    student = input("input id, name")
for i in C1.list_of_students:
    name= input("enter name course")
    grade = int(input("enter grade for: "))
    i.add_grade(name,grade)